=== cagriemreakin/SemanticWeb/DOM-SAX-XPATH/shop.xsd
<?xml version="1.0" encoding="utf-16"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="shop" type="shopType" />
  <xsd:complexType name="shopType">
    <xsd:sequence>
      <xsd:element name="customer_info" type="customer_infoType" />
    </xsd:sequence>
    <xsd:attribute name="xsi:noNamespaceSchemaLocation" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="customer_infoType">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" name="customer" type="customerType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="customerType">
    <xsd:sequence>
      <xsd:element name="cust_name" type="cust_nameType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:int" />
  </xsd:complexType>
  <xsd:complexType name="cust_nameType">
    <xsd:sequence>
      <xsd:element name="delivery_addr" type="delivery_addrType" />
      <xsd:element name="contact_num" type="xsd:int" />
      <xsd:element name="purchase_order_num" type="purchase_order_numType" />
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="purchase_order_numType">
    <xsd:sequence>
      <xsd:element name="items" type="itemsType" />
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="pun" type="xsd:string" />
  </xsd:complexType>
  <xsd:complexType name="itemsType">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" name="item" type="itemType" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="itemType">
    <xsd:sequence>
      <xsd:element name="item_descr" type="xsd:string" />
      <xsd:element name="quantity" type="xsd:int" />
    </xsd:sequence>
    <xsd:attribute name="in" type="xsd:int" />
  </xsd:complexType>
  <xsd:complexType name="delivery_addrType">
    <xsd:sequence>
      <xsd:element name="area_code" type="xsd:int" />
    </xsd:sequence>
    <xsd:attribute name="da" type="xsd:string" />
  </xsd:complexType>
</xsd:schema>

=== cagriemreakin/SemanticWeb/shop.xml
<?xml version='1.0' encoding='us-ascii'?> 

<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="shop.xsd">

<customer_info>

	<customer id="1">

	<cust_name name="Lars Ulrich">

	<delivery_addr da="cyprus">

		<area_code>187</area_code>

	</delivery_addr>

	<contact_num>123456789</contact_num>

	<purchase_order_num name="purchase" pun="5xyz">hello

		<items> 

			<item in="1">
				
				<item_descr>Gift Box</item_descr>

				<quantity>5</quantity>
			</item>
			<item in="2">
				<item_descr>Toy Box</item_descr>

				<quantity>7</quantity>
			</item>


		</items>

	</purchase_order_num>
  
  	</cust_name>

   </customer>

   <customer id="2">

	<cust_name name="James Hetfield">

	<delivery_addr da="cyprus">

		<area_code>187</area_code>

	</delivery_addr>

	<contact_num>123456789</contact_num>

	<purchase_order_num pun="5tzi">

		<items> 

			<item in="3">
				
				<item_descr>X Box</item_descr>

				<quantity>5</quantity>
			</item>

			<item in="2">
				<item_descr>Toy Box</item_descr>

				<quantity>7</quantity>

			</item>

		</items>

	</purchase_order_num>
  </cust_name>
   </customer>
   
   <customer id="3">

	<cust_name name="Kirk Hammet">

	<delivery_addr da="cyprus">

		<area_code>187</area_code>

	</delivery_addr>

	<contact_num>123456789</contact_num>

	<purchase_order_num name="purchase" pun="5xx">

		<items> 

			<item in="4">
				
				<item_descr>Playstation 4</item_descr>

				<quantity>10</quantity>
			</item>
			<item in="5">
				<item_descr>Wii U</item_descr>

				<quantity>12</quantity>
			</item>


		</items>

	</purchase_order_num>
  
  	</cust_name>

   </customer>

</customer_info>

</shop>
